language: php

php:
  - 7.1

env:
  - SYMFONY_DEPRECATIONS_HELPER: weak

cache:
  directories:
    - .composer/cache

before_install:
  - alias composer=composer\ -n && composer self-update

install:
  - cd demo
  - travis_retry composer global require hirak/prestissimo
  - travis_retry composer install --no-interaction

script:
  - vendor/behat/behat/bin/behat .

notifications:
  email:
    - rsantos@ynloultratech.com