services:
    # makes public all services by default
    _defaults: { public: true }

    Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaStorageProviderPool:
        class: Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaStorageProviderPool
        arguments:
            - !tagged media_service.storage_service_gateway

    Ynlo\GraphQLMediaServiceBundle\Controller\GetFileController:
        class: Ynlo\GraphQLMediaServiceBundle\Controller\GetFileController
        public: true
        arguments:
            - '@doctrine'
            - '%media_service_config%'
            - '@Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaStorageProviderPool'
            - !tagged media_service.extension

    Ynlo\GraphQLMediaServiceBundle\MediaServer\FileManager:
        class: Ynlo\GraphQLMediaServiceBundle\MediaServer\FileManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaStorageProviderPool'
            - '%media_service_config%'
            - !tagged media_service.extension

    Ynlo\GraphQLMediaServiceBundle\MediaServer\LocalMediaStorageProvider:
        class: Ynlo\GraphQLMediaServiceBundle\MediaServer\LocalMediaStorageProvider
        arguments: ['@router', '%kernel.secret%']
        tags:
          - { name: 'media_service.storage' }

    Ynlo\GraphQLMediaServiceBundle\MediaServer\Provider\DigitalOceanSpace:
        class: Ynlo\GraphQLMediaServiceBundle\MediaServer\Provider\DigitalOceanSpace
        tags:
            - { name: 'media_service.storage' }

    Ynlo\GraphQLMediaServiceBundle\Cache\MediaServerCacheWarmer:
        class: Ynlo\GraphQLMediaServiceBundle\Cache\MediaServerCacheWarmer
        arguments: ['@Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaServerMetadata']
        public: false
        tags:
            - { name: 'kernel.cache_warmer', priority: 200 }

    Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaServerMetadata:
        class: Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaServerMetadata
        arguments: ['@doctrine','@annotations.reader','%kernel.cache_dir%']

    Ynlo\GraphQLMediaServiceBundle\EventListener\Doctrine\MediaServerListener:
        class: Ynlo\GraphQLMediaServiceBundle\EventListener\Doctrine\MediaServerListener
        public: false
        arguments:
            - '@Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaServerMetadata'
            - '@Ynlo\GraphQLMediaServiceBundle\MediaServer\MediaStorageProviderPool'
            - !tagged media_service.extension
        tags:
            - { name: 'doctrine.event_subscriber' }

    Ynlo\GraphQLMediaServiceBundle\Form\TypeGuesser\FileTypeGuesser:
        arguments: ['@doctrine']
        public: false
        tags:
            - { name: 'form.type_guesser'}

    Ynlo\GraphQLMediaServiceBundle\Definition\UploadFileDefinitions:
        arguments: ['%media_service_config%']
        tags:
            - { name: 'graphql.definition_loader' }