#!/bin/bash

shell_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${shell_path}"
path=$(pwd)

echo Preparing...

rm -rf public/uploads
rm -rf uploads

bin/console cache:clear --env=dev --no-warmup -q
bin/console cache:warmup --env=dev -q
bin/console doctrine:schema:drop --force --full-database -q
bin/console doctrine:schema:create -q
bin/console doctrine:schema:update  --force -q
bin/console doctrine:fixtures:load -n -q
bin/console assets:install public --symlink
bin/console server:run --docroot=public